//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
        
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<div style=""display: flex; justify-content: center; display:flex; flex-direction: column; algin-content: center"">
<div style= ""background-color:rgba(0, 0, 0, 0.3);  border-radius: 25px;
  border: 2px;
  padding: 20px;
  width: 600px;
  height: 150px;"">
  <h3 style= ""color: white"">
    Gracias por ponerte en contacto con nosotros
  </h3>
 </div>
<div style=""display: flex; justify-content: center; display:flex; flex-direction: column; algin-content: center"">
<div style= ""background-color:rgba(0, 0, 0, 0.3);  border-radius: 25px;
  border: 2px;
  padding: 20px;
  width: 600px;
  height: 150px;"">
  <h3 style= ""color: white"">
    Gracias por ponerte en contacto con nosotros
  </h3>
 </div>
</div>")]
        public string cuerpo {
            get {
                return ((string)(this["cuerpo"]));
            }
        }
    }
}
